### ISSUE TITLE
Cannot use plugin when MySQL is not managed by Tutor

### ISSUE THREAD

**Issue by BbrSofiane** [hastexo/tutor-contrib-backup#29]
# Summary

When running a local deployment of tutor where MySQL is not managed by tutor, the plugin fails.

## What I did

When running 
```
tutor local backup
```

I got the following error:

```
ERROR: Service 'backup-job' depends on service 'mysql' which is undefined.
```

## What I expected to happen

I would expect this dependency to be contingent on `RUN_MYSQL` to be set to True in the tutor config. I'm happy to open a PR with a fix if that's ok.

**Comment by foadlind** [comment]
Hi @BbrSofiane,

You are correct. That dependency should only be there if `RUN_MYSQL` is set to True.

> I'm happy to open a PR with a fix if that's ok.

Yes, that's greatly appreciated!
