### ISSUE TITLE
No disk space in K8s

### ISSUE THREAD

**Issue by angonz** [hastexo/tutor-contrib-backup#40]
# Summary

In K8s, backup is failing because there is not enough disk space in the node to store the db dumps and temporary files

## What I did

Just running `tutor k8s backup` on an instance with large databases, or letting the cronjob run. The job fails and there are disk pressure alarms reported.

## What I expected to happen

Backup should happen normally

## What actually happened

Backup job fails.

## My environment

* Tutor version: 14.0.1
* `tutor-contrib-backup` version: 1.0.0
* Output of the backup/restore command/CronJob: 
container "backup" in pod "backup-restore-job-20220809082445-265rt" is not available
The node had condition: [DiskPressure].
The node was low on resource: ephemeral-storage. Container backup was using 7282412Ki, which exceeds its request of 0.

* Kubernetes versions: Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.13-eks-84b4fe6", GitCommit:"e1318dce57b3e319a2e3fecf343677d1c4d4aa75", GitTreeState:"clean", BuildDate:"2022-06-09T18:22:07Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

## Additional context

My mongodb dump is about 20Gi.

**Comment by foadlind** [comment]
@angonz what do you suggest the plugin should do in this case?

One way could be to add a [ephemeral-storage resource request](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#local-ephemeral-storage) to the jobs created by the plugin. The value of the request could be a config default that the user can override. But even then the Kubernetes controller would simply not run the job pod if it was not able to fulfill the request due to node disk pressure.

I suggest that, if possible, you increase the disk space available to the node or move the other pods to another node to reduce the disk pressure. Note that the jobs created by the plugin have a [`podAffinity` rule](https://github.com/hastexo/tutor-contrib-backup/blob/958c4ae3acffc44f51dc58a361aa597901c88326/tutorbackup/patches/k8s-jobs#L12) that mandate the jobs to run on the same node as the `caddy` pod.

**Comment by angonz** [comment]
Hi @foadlind for your reply!
I am working on a change that would use an ephemeral volume (not in the local storage, but in a PVC). It is basically a regular PVC, but that gets created and destroyed along with the POD when the job is called. 
However I got stuck in another problem that I reported in [another issue](https://github.com/hastexo/tutor-contrib-backup/issues/41). I guess once this is solved, I can continue with the PVC issue.

**Comment by fghaas** [comment]
@angonz You mean a [generic ephemeral volume](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes)? That's a good idea. It does bump the minimum required Kubernetes release though. Tutor doesn't say much about what Kubernetes releases it supports. The documentation [only states that it was "tested with server version 1.14.1 and client 1.14.3."](https://docs.tutor.overhang.io/k8s.html#version), in which inline volumes weren't available at all — but that is probably moot because hopefully nobody runs that version anymore. Still, do you have ideas for how to address that?

**Comment by angonz** [comment]
Well... I had to fix the [--all databases issue](https://github.com/hastexo/tutor-contrib-backup/issues/41) with [PR #43](https://github.com/hastexo/tutor-contrib-backup/pull/43). After that I was able to proceed and made a good progress on this. 
I created two ephemeral volumes, one for /data and another for /backup, and I got rid of the disk pressure issue.
Both MySQL and MongoDB dumps are created well. The tar takes 90mins to be created, but completes well and creates a 6Gi file out of the 20Gi original.
But then, the upload starts and stops immediately with a `Killed` message. 
The same configuration, with smaller MongoDB files upload well.

```
2022-08-24T21:31:57.033+0000    [######################..]  edxmongo.modulestore.structures  66050/69718  (94.7%)
2022-08-24T21:32:00.033+0000    [#######################.]  edxmongo.modulestore.structures  68380/69718  (98.1%)
2022-08-24T21:32:02.368+0000    [########################]  edxmongo.modulestore.structures  69718/69718  (100.0%)
2022-08-24T21:32:02.368+0000    done dumping edxmongo.modulestore.structures (69718 documents)
2022-08-24 21:32:02,538 INFO Complete. /data/mongodb_dump total size 19266894487 bytes.
2022-08-24 21:32:02,545 INFO Copying Caddy data to /data/caddy
2022-08-24 21:32:02,596 INFO Complete. /data/caddy total size 156106 bytes.
2022-08-24 21:32:02,596 INFO Creating archive /backup/backup.2022-08-24.tar.xz
2022-08-24 22:58:41,706 INFO Complete. /backup/backup.2022-08-24.tar.xz is 6219118968 bytes.
2022-08-24 22:58:42,670 INFO Uploading /backup/backup.2022-08-24.tar.xz to S3 bucket openedx-aulasneo-backup
Killed
```

Any idea why can this be?

**Comment by fghaas** [comment]
What exactly is getting "killed" here? Is it just the `backup_services.py` script inside the the backup pod, or the whole pod? In addition to the pod log, you may want to check the pod events list, or `kubectl describe` on either the pod or its parent CronJob.

If it's the pod that gets killed, and you have ruled out any remaining DiskPressure issues that might cause the pod to get evicted, maybe check if your Kubernetes sets a default value [for `activeDeadlineSeconds` in the job spec](https://kubernetes.io/docs/concepts/workloads/controllers/job/#job-termination-and-cleanup)? The generated job definitions don't set any, and to the best of my knowledge there is no upstream default either, but maybe EKS sets one?

**Comment by angonz** [comment]
Hi Florian! I didn't have much time lately. I can submit the PR as is, but couldn't find out yet what gets killed really. I supposed it's something related to the size of the Mongo DB, but I wanted first to have [issue #46](https://github.com/hastexo/tutor-contrib-backup/issues/46) fixed so I can try with a smaller db.

**Comment by angonz** [comment]
[PR #48](https://github.com/hastexo/tutor-contrib-backup/pull/48) submitted

**Comment by angonz** [comment]
Hi @fghaas, @foadlind!
First I wanted to thank you for your support and your patience for the changes I've requested! It's a great learning opportunity for me about working in collaborative projects and you guys have helped a lot.

Now I was able to test the plugin in AWS using K8s with multiple sites and works like charm _for small databases_. However now the pod suddenly ends with a _Killed_ message with one of my instances which has a ~19Gi Mongo DB. This is what I was able to catch: 

```
2022-09-16T20:20:49.403+0000    [########################]  edxmongo_mynamespace_prod.modulestore.structures  69724/69724  (100.0%)
2022-09-16T20:20:49.403+0000    done dumping edxmongo_mynamespace_prod.modulestore.structures (69724 documents)
2022-09-16 20:20:49,426 INFO Complete. /data/mongodb_dump total size 19221829254 bytes.
2022-09-16 20:20:49,430 INFO Copying Caddy data to /data/caddy
2022-09-16 20:20:49,507 INFO Complete. /data/caddy total size 159627 bytes.
2022-09-16 20:20:49,519 INFO Creating archive /data/backup/backup.2022-09-16.tar.xz
2022-09-16 21:47:06,551 INFO Complete. /data/backup/backup.2022-09-16.tar.xz is 6203923076 bytes.
2022-09-16 21:47:07,462 INFO Uploading /data/backup/backup.2022-09-16.tar.xz to S3 bucket openedx-aulasneo-backup-mynamespace-prod
Killed
Fri Sep 16 18:47:25 -03 2022
Name:                      backup-restore-job-20220916171754-p9txd
Namespace:                 mynamespace-prod
Priority:                  0
Node:                      ip-10-0-4-229.ec2.internal/10.0.4.229
Start Time:                Fri, 16 Sep 2022 17:18:11 -0300
Labels:                    app.kubernetes.io/instance=openedx-kBRnaGZpR7SoKt4ST6vpG8ut
                           app.kubernetes.io/managed-by=tutor
                           app.kubernetes.io/part-of=openedx
                           controller-uid=d55024a4-ab1d-461c-abdd-0cb760471200
                           job-name=backup-restore-job-20220916171754
Annotations:               app.kubernetes.io/version: 14.0.5
                           kubernetes.io/psp: eks.privileged
Status:                    Terminating (lasts <invalid>)
Termination Grace Period:  30s
IP:                        10.0.4.13
IPs:
  IP:           10.0.4.13
Controlled By:  Job/backup-restore-job-20220916171754
Containers:
  backup:
    Container ID:  containerd://73657e061d265ef7caffe3de77dd21782f9af3e27c06eef57bcc0e8a44a186ea
    Image:         212507341974.dkr.ecr.us-east-1.amazonaws.com/campus-prod/backup:test202209131928
    Image ID:      212507341974.dkr.ecr.us-east-1.amazonaws.com/campus-prod/backup@sha256:cb0a8fb07f9acf4b85e8b3acda384c8b5cc177fdccfc3641cde4a1324da5003d
    Port:          <none>
    Host Port:     <none>
    Args:
      sh
      -e
      -c
      python backup_services.py --upload
    State:          Running
      Started:      Fri, 16 Sep 2022 18:47:25 -0300
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Fri, 16 Sep 2022 17:18:16 -0300
      Finished:     Fri, 16 Sep 2022 18:47:24 -0300
    Ready:          True
    Restart Count:  1
    Environment:
      MYSQL_HOST:                       xxxxxxxxxxx.us-east-1.rds.amazonaws.com
      MYSQL_PORT:                       3306
      MYSQL_ROOT_USERNAME:              xxxxxxxxxxx
      MYSQL_ROOT_PASSWORD:              xxxxxxxxxxx
      MYSQL_DATABASES:                  edxdb_mynamespace_prod notes_mynamespace_prod discovery_mynamespace_prod
      MONGODB_HOST:                     ip-10-0-9-66.ec2.internal
      MONGODB_PORT:                     27017
      MONGODB_USERNAME:                 xxxxxxxxxxx
      MONGODB_PASSWORD:                 xxxxxxxxxxx
      MONGODB_DATABASES:                forum_mynamespace_prod edxmongo_mynamespace_prod
      MONGODB_AUTHENTICATION_DATABASE:  admin
      S3_SIGNATURE_VERSION:             s3v4
      S3_ADDRESSING_STYLE:              auto
      S3_REGION_NAME:                   us-east-1
      S3_USE_SSL:                       True
      S3_ACCESS_KEY:                    xxxxxxxxxxx
      S3_SECRET_ACCESS_KEY:             xxxxxxxxxxx
      S3_BUCKET_NAME:                   openedx-aulasneo-backup-mynamespace-prod
    Mounts:
      /caddy/ from data (rw)
      /data/ from backup-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wsc8b (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  backup-volume:
    Type:          EphemeralVolume (an inline specification for a volume that gets created and deleted with the pod)
    StorageClass:  
    Volume:        
    Labels:            <none>
    Annotations:       <none>
    Capacity:      
    Access Modes:  
    VolumeMode:    Filesystem
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  caddy
    ReadOnly:   false
  kube-api-access-wsc8b:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 12000s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 12000s
Events:
  Type    Reason   Age               From     Message
  ----    ------   ----              ----     -------
  Normal  Pulled   5s (x2 over 89m)  kubelet  Container image "212507341974.dkr.ecr.us-east-1.amazonaws.com/campus-prod/backup:test202209131928" already present on machine
  Normal  Created  5s (x2 over 89m)  kubelet  Created container backup
  Normal  Started  5s (x2 over 89m)  kubelet  Started container backup
  Normal  Killing  3s                kubelet  Stopping container backup
LAST SEEN   TYPE      REASON                 OBJECT                                        SUBOBJECT                       SOURCE                                MESSAGE                                                                                                                         FIRST SEEN   COUNT   NAME
7s          Normal    Pulled                 pod/backup-restore-job-20220916171754-p9txd   spec.containers{backup}         kubelet, ip-10-0-4-229.ec2.internal   Container image "212507341974.dkr.ecr.us-east-1.amazonaws.com/campus-prod/backup:test202209131928" already present on machine   89m          2       backup-restore-job-20220916171754-p9txd.171570a645d0faf4
7s          Normal    Created                pod/backup-restore-job-20220916171754-p9txd   spec.containers{backup}         kubelet, ip-10-0-4-229.ec2.internal   Created container backup                                                                                                        89m          2       backup-restore-job-20220916171754-p9txd.171570a64886d4f0
7s          Normal    Started                pod/backup-restore-job-20220916171754-p9txd   spec.containers{backup}         kubelet, ip-10-0-4-229.ec2.internal   Started container backup                                                                                                        89m          2       backup-restore-job-20220916171754-p9txd.171570a65016d0e1
5s          Normal    Killing                pod/backup-restore-job-20220916171754-p9txd   spec.containers{backup}         kubelet, ip-10-0-4-229.ec2.internal   Stopping container backup                                                                                                       5s           1       backup-restore-job-20220916171754-p9txd.17157584214ad053
6s          Normal    SuccessfulDelete       job/backup-restore-job-20220916171754                                         job-controller                        Deleted pod: backup-restore-job-20220916171754-p9txd                                                                            6s           1       backup-restore-job-20220916171754.17157583ea1f4865
6s          Warning   BackoffLimitExceeded   job/backup-restore-job-20220916171754                                         job-controller                        Job has reached the specified backoff limit                                                                                     6s           1       backup-restore-job-20220916171754.17157583ea1f73f3
52m         Normal    Scheduled              pod/panorama-elt-27722695-k8ff8                                               default-scheduler                     Successfully assigned mynamespace-prod/panorama-elt-27722695-k8ff8 to ip-10-0-5-4.ec2.internal                                       52m          1       panorama-elt-27722695-k8ff8.171572a753165bad
52m         Normal    Pulled                 pod/panorama-elt-27722695-k8ff8               spec.containers{panorama-elt}   kubelet, ip-10-0-5-4.ec2.internal     Container image "docker.io/aulasneo/panorama-elt:0.1.8a" already present on machine                                             52m          1       panorama-elt-27722695-k8ff8.171572a77c538041
52m         Normal    Created                pod/panorama-elt-27722695-k8ff8               spec.containers{panorama-elt}   kubelet, ip-10-0-5-4.ec2.internal     Created container panorama-elt                                                                                                  52m          1       panorama-elt-27722695-k8ff8.171572a77e7372d5
52m         Normal    Started                pod/panorama-elt-27722695-k8ff8               spec.containers{panorama-elt}   kubelet, ip-10-0-5-4.ec2.internal     Started container panorama-elt                                                                                                  52m          1       panorama-elt-27722695-k8ff8.171572a7940c595b
52m         Normal    SuccessfulCreate       job/panorama-elt-27722695                                                     job-controller                        Created pod: panorama-elt-27722695-k8ff8                                                                                        52m          1       panorama-elt-27722695.171572a751cd1d0a
52m         Normal    Completed              job/panorama-elt-27722695                                                     job-controller                        Job completed                                                                                                                   52m          1       panorama-elt-27722695.171572aa2863bd61
52m         Normal    SuccessfulCreate       cronjob/panorama-elt                                                          cronjob-controller                    Created job panorama-elt-27722695                                                                                               52m          1       panorama-elt.171572a748cf81ea
52m         Normal    SawCompletedJob        cronjob/panorama-elt                                                          cronjob-controller                    Saw completed job: panorama-elt-27722695, status: Complete                                                                      52m          1       panorama-elt.171572aa2a151358
52m         Normal    SuccessfulDelete       cronjob/panorama-elt                                                          cronjob-controller                    Deleted job panorama-elt-27722515                                                                                               52m          1       panorama-elt.171572aa2b548afb
```

Note that the pod is killed 20 seconds after it starts uploading the tarfile, which took ~87 minutes to be created.

I increased the job's tolerationSeconds to 200 minutes with the same result.

**Comment by foadlind** [comment]
@angonz I'm going have a wild guess here and say that this might be due to boto3 S3 client using too much memory when uploading the large file. This would then bring the pod to the memory usage limit and the controller would kill the pod to prevent it from overwhelming the node. Do you have any means of monitoring the memory usage of that pod, or the node it ran on, in your K8s cluster? 
If this is the reason, you might want to experiment with boto3's `TransferConfig` settings in the [`upload_file` method](https://boto3.amazonaws.com/v1/documentation/api/1.16.53/reference/services/s3.html?highlight=upload_file#S3.Client.upload_file) to see if you can reduce the memory usage somehow.
Another cause could be some sort of limitation on the S3 side. But I would expect such limitation to be reported as an error by S3 and logged in the container. To rule this out, you could try to upload the tarfile manually or using a S3 CLI tool like `AWS CLI` or `s3cmd`.

**Comment by angonz** [comment]
> Do you have any means of monitoring the memory usage of that pod, or the node it ran on, in your K8s cluster? Could you see any spikes in memory usage then?
Actually memory and cpu is at the top of the pod all the time!
> Are there any MemoryPressure events registered on the node that you could correlate to the timestamp of this job (specifically when the uploading starts)?
Not at all, no pressure events of any kind. That's what surprises me... nothing but the `Killed` message.

**Comment by fghaas** [comment]
The `python` process exiting with error 137 means it has received `SIGKILL`. There are two things that I could think of:

1. Something kills the process because it's using too much memory.
2. Job exceeds its `activeDeadlineSeconds` limit.

We don't set `activeDeadlineSeconds` in the job definition, and to the best of my knowledge Kubernetes doesn't set a default value for that either. 

> Note that the pod is killed 20 seconds after it starts uploading the tarfile, which took ~87 minutes to be created.

**If** we're dealing with a memory issue, then this would imply it's the upload that does it... but that's a bit weird too since, if I understand correctly, the `upload_file()` method we are using would transparently handle multipart uploads.

So I think our real problem — again, *if* we're dealing with a memory issue — is actually this:

https://github.com/hastexo/tutor-contrib-backup/blob/e1d733928cdf4c38e42217f4a68ebf80f15010a5/tutorbackup/templates/backup/build/backup/backup_services.py#L160-L163

Here we read the whole tarball into memory in order to work out our checksum. @foadlind, is there a less memory-hungry way for us to do this?

**Comment by foadlind** [comment]
I completely forgot about the checksum calculation! I guess we could read the file in chunks. I'll give it a try.

**Comment by foadlind** [comment]
In #52 I changed the checksum calculation so that it reads the file in chunks instead. @angonz could you test it with your large databases and let us know?

**Comment by angonz** [comment]
Worked!!!!

```
2022-09-22T11:37:08.391+0000    [########################]  edxmongo_capnet_prod.modulestore.structures  69724/69724  (100.0%)
2022-09-22T11:37:08.391+0000    done dumping edxmongo_capnet_prod.modulestore.structures (69724 documents)
2022-09-22 11:37:08,403 INFO Complete. /data/mongodb_dump total size 19221829254 bytes.
2022-09-22 11:37:08,404 INFO Copying Caddy data to /data/caddy
2022-09-22 11:37:08,451 INFO Complete. /data/caddy total size 159627 bytes.
2022-09-22 11:37:08,460 INFO Creating archive /data/backup/backup.2022-09-22.tar.xz
2022-09-22 13:03:09,855 INFO Complete. /data/backup/backup.2022-09-22.tar.xz is 6203906884 bytes.
2022-09-22 13:03:10,786 INFO Calculating checksum for /data/backup/backup.2022-09-22.tar.xz
2022-09-22 13:03:55,984 INFO Uploading /data/backup/backup.2022-09-22.tar.xz to S3 bucket mybucket
2022-09-22 13:04:43,339 INFO Uploaded /data/backup/backup.2022-09-22.tar.xz to mybucket.
2022-09-22 13:04:43,356 INFO Checking uploaded file's integrity ...
2022-09-22 13:04:43,451 INFO File integrity verified.
Version ID: 'ZxYLnXIK7V2hmOleWh3JEL_7MvXo0Vxh'
Size: 6203906884 bytes
Checksum: '58da782824f8701f37e281406227136c'
```

**Comment by foadlind** [comment]
Nice! :tada: :clap: 

[v1.2.0](https://github.com/hastexo/tutor-contrib-backup/releases/tag/v1.2.0) now includes the checksum calculation fix (#52) and the ephemeral volumes feature (#48).

**Comment by fghaas** [comment]
Yeah I also find it interesting to see how the timing plays out there.

* Nearly 1½ hours for creating the tarball.
* 45 seconds for calculating the checksum.
* Less than 50 seconds for uploading the tarball into S3.

**Comment by fghaas** [comment]
@foadlind, I think with @angonz' confirmation we can close this one as having been fixed by #48 and #52 — would you agree?

**Comment by foadlind** [comment]
Yes, I agree.

**Comment by fghaas** [comment]
Great. Thanks everyone!

And on this note, Andrés:

> First I wanted to thank you for your support and your patience for the changes I've requested! It's a great learning opportunity for me about working in collaborative projects and you guys have helped a lot.

You're most welcome!

**Comment by angonz** [comment]
Hi! Do you have public docker image? By default it tries to fetch `docker.io/backup:1.2.0` which does not exist. Or should I build an push to my own repo?

**Comment by fghaas** [comment]
Yes, you should. Please see the [Usage instructions](https://github.com/hastexo/tutor-contrib-backup#usage).

**Comment by angonz** [comment]
It's ok for local, but K8s needs a public repo to pull the image. I can use my own registry. I was wondering if you had already a public image. Or am I missing something?

**Comment by fghaas** [comment]
No, at this point we don't yet have a public image. But, for any Tutor environment on Kubernetes that uses MFEs (and at this point, pretty much any Tutor environment should use MFEs), you need your own registry anyway — [because every Tutor instance needs its own private MFE image](https://github.com/overhangio/tutor-mfe#running-mfes-on-kubernetes). So just publish your backup images on the same registry that also hosts your MFE images.
