### ISSUE TITLE
Issues backing up `--all-databases`

### ISSUE THREAD

**Issue by angonz** [hastexo/tutor-contrib-backup#41]
# Summary

When backing up MySQL databases, the plugin [dumps all databases](https://github.com/hastexo/tutor-contrib-backup/blob/958c4ae3acffc44f51dc58a361aa597901c88326/tutorbackup/templates/backup/build/backup/backup_services.py#L50).
Specially in Kubernetes deployments, there are some problems with this approach:

- I may be using many databases for different LMS, when deploying many LMS in the same cluster sharing the same MySQL engine (only in Kubernetes). I would like each instance of the plugin to backup only the databases of the corresponding LMS.
- I may be using more databases in the same MySQL cluster that I don't want to backup here
- When using AWS Aurora, it will throw an error `mysqldump: Couldn't execute 'SHOW CREATE PROCEDURE `rds_import_binlog_ssl_material`': Failed to load routine mysql.rds_import_binlog_ssl_material. The table mysql.proc is missing, corrupt, or contains bad data`. This is caused by a [limitation of AWS Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql_rds_import_binlog_ssl_material.html) for MySQL 5.7 (works only in 5.6)
- Additionally, using `--all-databases` may cause permissions issues with the internal tables, as the master user is not allowed to access them. 

## What I did

This impacts mostly Kubernets with AWS Aurora for MySQL 5.7.

## What I expected to happen

I would like to have an option to select the databases I want to backup. This will have to include the edxapp db of course, but also discovery, ecommerce, notes, and any other db that may be used by other plugins. It might be a challenge, as some of them may not even exist.

## My environment

* Tutor version: 14.0.1
* `tutor-contrib-backup` version: 1.0.0
* AWS Aurora RDS for MySQL 5.7

**Comment by fghaas** [comment]
@angonz Thanks for the report! Up front, please understand that we don't use Aurora (or any AWS services, for that matter), so our testing capabilities and need for support for Aurora are somewhat limited.

Basically I think the `--all-databases` default is perfectly sound. We could support a `config.yml` variable named `BACKUP_MYSQL_DATABASES` that, if set, expects a YAML list of databases to back up, at which point it would only back up (and restore) the databases listed. 

In that case, if you set

```yaml
BACKUP_MYSQL_DATABASES:
  - foo
  - bar
  - baz
```

it would not use `mysqldump --all-databases`, but instead `mysql --databases foo bar baz`.

Please note that in this case, the onus would be on the user to update this list if they ever add a plugin to their Tutor configuration that touches another database.

Would you like to send us a PR for that?

**Comment by angonz** [comment]
Hi!
I've created [PR #43](https://github.com/hastexo/tutor-contrib-backup/pull/43) for this. I've checked myself and works well. Please check and let me know.

**Comment by fghaas** [comment]
Fixed in #43, and we'll cut a new release once #44 lands. Thank you!
