### ISSUE TITLE
Dump only this instance mongo databases

### ISSUE THREAD

**Issue by angonz** [hastexo/tutor-contrib-backup#46]
# Summary

Hi! It's me again 😊
Something similar to MySQL happens in MongoDB. All databases are dumped, which is a problem when using the same Mongo cluster for many LMS.

## What I did

tutor k8s backup

## What I expected to happen

Only the two databases related to this LMS should be backed up: one for the courses structures and another for forum

## What actually happened

All databases are backed up, including others not related to this LMS.

## My environment

Please add some information about the environment that you’re working in. At a minimum, include these items:

* Tutor version: 14.0.1
* `tutor-contrib-backup` version: 1.1.0

## Additional context

Multiple LMS's share the same MongoDB cluster.
There is a plan to deprecate MongoDB in the short term. I wouldn't expect the number of Mongo databases to increase in the future, so I wouldn't spend a lot of effort in a flexible structure.
If you don't disagree, I would just change the mongodump command and dump only these two databases.

**Comment by fghaas** [comment]
Ummmm... I don't know off the top of my head what the implications of not including the `admin` database are. @foadlind, any thoughts on that?

**Comment by foadlind** [comment]
Now that I think about it, maybe we shouldn't backup and restore the `admin` database at all.

The `admin` database holds authentication and authorization information for MongoDB. By default Tutor doesn't set a username and password for MongoDB user, so both the backup and restore scripts can work with the MongoDB instance without needing to authenticate. In that case, on a self-managed MongoDB, we can overwrite the `admin` database with no issues (as we are doing now).

But if the MongoDB instance we are restoring to is managed (for example by AWS, Atlas, etc) then `admin` might already be populated and the user will need to populate `MONGODB_USERNAME`, and `MONGODB_PASSWORD` config parameters in Tutor. In such a case the [restore script will use those to authenticate](https://github.com/hastexo/tutor-contrib-backup/blob/39d68b04397859d8c0cd0e2094eff839bcb89e53/tutorbackup/templates/backup/build/backup/restore_services.py#L71) `mongorestore` with MongoDB. In that scenario we don't want to overwrite the `admin` database.

So I think @angonz's suggestion is probably a better default behavior.

**Comment by fghaas** [comment]
Alright then! See, that's why I asked. :) @angonz, will you be sending a PR? We'd much appreciate that.

**Comment by foadlind** [comment]
I'll submit PR for this.

**Comment by foadlind** [comment]
@angonz could you test the solution in #49 and let us know if you run into any issues?

**Comment by angonz** [comment]
I see an `admin` and a `config` databases. They probably include authentication info. We can include them also in each backup.



De: Florian Haas ***@***.***>
Fecha: miércoles, 31 de agosto de 2022, 16:12
Para: hastexo/tutor-contrib-backup ***@***.***>
CC: Andres Gonzalez ***@***.***>, Author ***@***.***>
Asunto: Re: [hastexo/tutor-contrib-backup] Dump only this instance mongo databases (Issue #46)

Ummmm... I don't know off the top of my head what the implications of not including the admin database are. @foadlind<https://github.com/foadlind>, any thoughts on that?
