### ISSUE TITLE
Backup fails in RDS with MySQL 8 

### ISSUE THREAD

**Issue by angonz** [hastexo/tutor-contrib-backup#77]
# Summary

Backup fails in Aurora RDS with MySQL 8 with this stack trace:

```
mysqldump: Couldn't execute 'FLUSH TABLES WITH READ LOCK': Access denied for user 'myuser'@'%' (using password: YES) (1045)
Traceback (most recent call last):
  File "backup_services.py", line 243, in <module>
    main()
  File "/s3/venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/s3/venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/s3/venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/s3/venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "backup_services.py", line 227, in main
    mysqldump()
  File "backup_services.py", line 66, in mysqldump
    check_call(cmd,
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'mysqldump --databases openedx_db --add-drop-database --routines --events --single-transaction --quick --quote-names --max-allowed-packet=16M --host=myhost.rds.amazonaws.com --port=3306 --user=myuser --password=mypassword' returned non-zero exit status 2.
```

## What I did

It happens after moving to MySQL 8 in a new Aurora RDS cluster, when running `tutor k8s backup`.

## My environment

* Tutor version: 16.1.8
* `tutor-contrib-backup` version: 3.1.0

## Additional context

Seems to be related to this [AWS issue](https://repost.aws/es/knowledge-center/mysqldump-error-rds-mysql-mariadb) for `FLUSH TABLES WITH READ LOCK` error.

**Comment by fghaas** [comment]
@angonz Thanks for the report. We can't reproduce this as we don't use AWS, so we'll have to go by the available documentation and [the issue you linked](https://repost.aws/es/knowledge-center/mysqldump-error-rds-mysql-mariadb) doesn't appear to explain the issue — as it's talking about the `--master-data` option for `mysqldump`, which we don't use.

However, [this page](https://docs.digitalocean.com/support/how-do-i-fix-the-mysqldump-error-couldnt-execute-flush-tables-access-denied/) from the DigitalOcean docs appears to indicate that it might also be `--single-transaction` that's causing this.

Can you run a local patch that removes `--single-transaction` from the `mysqldump` arguments, and see if that makes a difference?

**Comment by angonz** [comment]
Hi @fghaas! Thanks for your prompt response.

I tried removing the `--single-transaction` and yes, it fixes the problem, showing this warning:

```
Warning: A partial dump from a server that has GTIDs will by default include the GTIDs of all transactions, even those that changed suppressed parts of the database. If you don't want to restore GTIDs, pass --set-gtid-purged=OFF. To make a complete dump, pass --all-databases --triggers --routines --events. 
Warning: A dump from a server that has GTIDs enabled will by default include the GTIDs of all transactions, even those that were executed during its extraction and might not be represented in the dumped data. This might result in an inconsistent data dump. 
In order to ensure a consistent backup of the database, pass --single-transaction or --lock-all-tables or --master-data. 
```

I think that the function of this setting is to avoid the app to make changes in the db and causing corrupt dumps for incomplete transactions. Any option will trigger the `FLUSH TABLES WITH READ LOCK` and cause the same issue. 

I can make a PR removing the `--single-transaction` at all, or including a setting to let the end user choose. What do you think?

**Comment by fghaas** [comment]
> I can make a PR removing the `--single-transaction` at all,

No, I don't think this is an option. `--single-transaction` is there for a reason, namely to produce a consistent backup. And it appears to work everywhere _except_ on Aurora. Which means we need an _optional_ workaround for the Aurora breakage; we can't make it less reliable _for everyone_ just because Aurora is broken in this regard.

> or including a setting to let the end user choose.

This is the correct approach. If you could, please create a PR that defines a boolean variable named `BACKUP_MYSQL_SINGLE_TRANSACTION`, defaulting to `True`, and then adds the `--single-transaction` CLI option based on its truth value.

**Comment by fghaas** [comment]
@angonz, another thought: why exactly would someone using Aurora want to use this plugin, rather than [follow the AWS recommendations for backing up Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html)?

**Comment by angonz** [comment]
> @angonz, another thought: why exactly would someone using Aurora want to use this plugin, rather than [follow the AWS recommendations for backing up Aurora](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Managing.Backups.html)?

The reason is that the AWS solution backs up all the cluster, and cannot backup only selected databases. In our case, we host many Open edX instances in the same DB cluster. Restoring a db can cause data loss, so a full restore for only one site will impact all others.

**Comment by fghaas** [comment]
@angonz, just checking: are you still planning to submit a PR that makes `--single-transaction` configurable?

**Comment by angonz** [comment]
Hi! Sorry for the delay.

Yes, I will do it.

**Comment by angonz** [comment]
Hi @fghaas, we are reviewing this, because I also detected that the restore would need to be modified as it also tries to [flush logs](https://github.com/hastexo/tutor-contrib-backup/blob/14f937af16eb05b65c009628f3c7761dd68c17e6/tutorbackup/templates/backup/build/backup/restore_services.py#L57-L66). I didn't test it buy I suspect it will also have issues.

I'm starting to think that Aurora is not a good option to host MySQL for Open edX.

**Comment by fghaas** [comment]
Well if flushing logs is a problem, then you can also add a `BACKUP_MYSQL_FLUSH_LOGS' option, and handle it the same way as `BACKUP_MYSQL_SINGLE_TRANSACTION`: default to `True`, and make calling `mysqladmin flush-logs` conditional on it.
