### ISSUE TITLE
Error creating backup image

### ISSUE THREAD

**Issue by sbernesto** [hastexo/tutor-contrib-backup#86]
Error creating backup image

Following the installation steps, when executing the tutor images build backup command, I get the following error:

```
ubuntu@tutor:~$ tutor images build backup
Building image docker.io/backup:3.3.0
docker buildx build --tag=docker.io/backup:3.3.0 --output=type=docker --cache-from=type=registry,ref=docker.io/backup:3.3.0-cache /home/ubuntu/.local/share/tutor/env/plugins/backup/build/backup
[+] Building 2.7s (14/14) FINISHED                                                            docker:default
 => [internal] load build definition from Dockerfile                                                    0.1s
 => => transferring dockerfile: 881B                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                         1.3s
 => [internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                         0.0s
 => ERROR importing cache manifest from docker.io/backup:3.3.0-cache                                    0.6s
 => [1/8] FROM docker.io/library/ubuntu:20.04@sha256:fa17826afb526a9fc7250e0fbcbfd18d03fe7a54849472f86  0.1s
 => => resolve docker.io/library/ubuntu:20.04@sha256:fa17826afb526a9fc7250e0fbcbfd18d03fe7a54849472f86  0.1s
 => [internal] load build context                                                                       0.1s
 => => transferring context: 111B                                                                       0.0s
 => CACHED [2/8] RUN apt-get update &&     apt-get install -y curl gnupg                                0.0s
 => CACHED [3/8] RUN curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | gpg --dearmor > /u  0.0s
 => CACHED [4/8] RUN python3 -m venv /s3/venv/                                                          0.0s
 => CACHED [5/8] RUN pip install --upgrade pip &&     pip install boto3 click &&     mkdir data backup  0.0s
 => CACHED [6/8] COPY backup_services.py .                                                              0.0s
 => CACHED [7/8] COPY restore_services.py .                                                             0.0s
 => CACHED [8/8] COPY s3_client.py .                                                                    0.0s
 => exporting to image                                                                                  0.0s
 => => exporting layers                                                                                 0.0s
 => => writing image sha256:268da13d883a1064c70fa2e78f29d52cf5723fd2bcfaf4f31ef52014cd0e18f0            0.0s
 => => naming to docker.io/library/backup:3.3.0                                                         0.0s
------
 > importing cache manifest from docker.io/backup:3.3.0-cache:
------

 2 warnings found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 2)
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 11)
 
```

tutor, version 18.1.3
tutor-contrib-backup@v3.3.0

**Comment by fghaas** [comment]
@sbernesto You will have to override `BACKUP_DOCKER_IMAGE` in your `config.yml`, pointing the registry prefix to `localhost:5000` or whatever other registry (Harbor, GitLab, etc.) you are using to manage your locally built images with.

**Comment by sbernesto** [comment]
Hi,
 I don't have anything that overrides the BACKUP_DOCKER_IMAGE on my config.yml or uses the other apps you mention.

**Comment by fghaas** [comment]
Yes, and I'm telling you that that's a problem. :) If you're building a local image, and you're then trying to build and subsequently push it to `docker.io`, as `docker.io/library/backup:3.3.0`, that won't work.

Besides, you didn't give much information as to how your build is actually failing. I see just one `ERROR` message in your build log, and that's not a fatal one, it's just telling you that it's unable to populate the build cache. So what exactly is the step that is causing your build to fail?

**Comment by fghaas** [comment]
Also, is there a particular reason why you chose to ignore/delete pretty much the entirety of the bug report template?

**Comment by sbernesto** [comment]
I'm not doing anything special that isn't on their plugin usage page.

I installed the plugin, enabled it, and then tried to build the image.

The only thing I found in a log is the following:

```
dockerd[1797]: time="2024-10-01T07:50:17.799417931Z" level=info msg="trying next host" error="pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" host=registry-1.docker.io

```

**Comment by fghaas** [comment]
I'm very sorry. You have declined to include the information that we're asking for in the bug report template. You are asserting that you are having a build failure, but you are refusing to give the console logs that show that failure. You are not answering my questions as to what your failure actually is. You are ignoring my suggestion to define `BACKUP_DOCKER_IMAGE`. 

Regretfully, I cannot help you on that basis. I have updated the README [with more information on building images](https://github.com/hastexo/tutor-contrib-backup/blob/main/README.md#building-the-image); I hope that clarifies things.

I will proceed to close this issue now. If you're still seeing build issues, please file a bug report [using the proper template](https://github.com/hastexo/tutor-contrib-backup/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=).
