### ISSUE TITLE
Tutor 18 not supported ?

### ISSUE THREAD

**Issue by mboisson** [hastexo/tutor-contrib-backup#91]
Hi,
Sorry for not filling all the sections, but this is a simple (I hope) question. 

The compatibility matrix table states that for Redwood, it requires the plugin version >= 4... but the latest release is 3.3. 

Is that to say that Redwood is not supported yet ? 

Thanks

**Comment by fghaas** [comment]
https://github.com/hastexo/tutor-contrib-backup/pull/89
